"""Finding knowledge registry - the machine-readable explanation of every finding.

This is the source of truth an AI coding agent (or the API/MCP) queries to understand and safely fix
a single finding. It is the structured, machine-consumable counterpart to docs/KNOWLEDGE_BASE.md:
near-identical findings (a check's pass/fail/length variants) share one card. `explain(finding_id)`
resolves any finding id the engine can emit to its card.

Pure data + lookup. No network, no model, no side effects.
"""

from __future__ import annotations

# category: deterministic_patch | structured_ai_task | human_decision | informational
# can_astova_generate: deterministic | ai_assisted | no
# agent_can_automate: always | usually | sometimes | never

_CARDS: list[dict] = [
    {
        "key": "title", "findings": ["title.missing", "title.length"],
        "name": "Page title", "category": "structured_ai_task",
        "can_astova_generate": "deterministic", "agent_can_automate": "usually", "human_review_required": True,
        "summary": "The page has no <title>, or one outside the readable 15-60 character band.",
        "why": "AI answer engines use the <title> as the page's canonical label when they index, chunk and cite it. No title means no name to cite by; a poor one carries no topical signal.",
        "how_to_fix": "Add exactly one descriptive <title> of ~50-60 characters in the <head> that names the specific page topic (not just the brand), front-loading the distinctive words.",
        "agent_guidance": "Find where head metadata is set (Next.js Metadata API in layout/page; Astro layout head; WP theme/SEO plugin). Set a unique, topic-led title. Do not duplicate the brand on every page or exceed ~60 chars. Astova can deterministically draft one from the H1, but a human/AI should refine for quality.",
        "verification": "Re-scan: title.missing clears and title.length is PASS (15-60 chars).",
        "frameworks": {"nextjs": "metadata.title in layout.tsx/page.tsx", "astro": "<title> in the layout head", "wordpress": "theme title tag / SEO plugin", "static": "<title> in <head>"},
        "related": ["meta.description.missing", "h1.missing"],
    },
    {
        "key": "meta_description", "findings": ["meta.description.missing", "meta.description.length"],
        "name": "Meta description", "category": "structured_ai_task",
        "can_astova_generate": "deterministic", "agent_can_automate": "usually", "human_review_required": True,
        "summary": "The page has no meta description, or one outside ~80-160 characters.",
        "why": "The meta description is a compact summary engines may lift as a snippet and use to judge relevance when deciding whether to surface or cite the page.",
        "how_to_fix": "Add a <meta name=\"description\"> of ~120-160 characters that accurately summarises the page in plain language.",
        "agent_guidance": "Set it where head metadata lives. Astova can draft one from the first paragraph/OG description deterministically, but quality is editorial - propose for review and never invent claims not on the page.",
        "verification": "Re-scan: meta.description.missing clears and meta.description.length is PASS.",
        "frameworks": {"nextjs": "metadata.description", "astro": "<meta> in layout head", "wordpress": "SEO plugin", "static": "<meta name=description>"},
        "related": ["title.missing", "opengraph"],
    },
    {
        "key": "headings", "findings": ["h1.missing", "h1.multiple", "h1.ok", "headings.structure", "onpage.heading_order"],
        "name": "Headings and H1", "category": "structured_ai_task",
        "can_astova_generate": "no", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "Exactly one H1 should name the page; subheadings should exist and not skip levels.",
        "why": "Engines use the heading outline to understand the page's structure and to locate the answer to a question. A missing or duplicated H1, or a skipped level, blurs that map.",
        "how_to_fix": "Use one H1 that states the page topic, then h2/h3 subheadings in order (do not jump h1 -> h3).",
        "agent_guidance": "Find the template/markdown. Promote the page's main title to a single <h1>; demote extra H1s to H2. Add subheadings where content shifts topic. Do not restructure semantics or break a valid HTML5 sectioned outline. Editing heading TEXT is editorial - keep it faithful.",
        "verification": "Re-scan: h1.ok PASS (exactly one H1), headings.structure PASS, onpage.heading_order PASS.",
        "frameworks": {"nextjs": "the page/MDX/component markup", "astro": ".astro/.md content", "wordpress": "post/template headings", "static": "<h1>/<h2> in HTML"},
        "related": ["geo.no_content", "geo.aeo"],
    },
    {
        "key": "canonical", "findings": ["canonical"],
        "name": "Canonical tag", "category": "deterministic_patch",
        "can_astova_generate": "deterministic", "agent_can_automate": "always", "human_review_required": False,
        "summary": "The page should declare a single self-referencing canonical URL.",
        "why": "A clear canonical tells engines which URL is authoritative, so citations and signals consolidate on one address instead of fragmenting across duplicates.",
        "how_to_fix": "Add one <link rel=\"canonical\" href=\"<absolute self URL>\"> in the <head>. Remove conflicting or cross-page canonicals.",
        "agent_guidance": "Inject a self-referencing absolute canonical via the framework's metadata layer. Deterministic and low risk. Do NOT point the canonical at a different page unless that is genuinely intended (it de-indexes this one). Ensure exactly one.",
        "verification": "Re-scan: canonical PASS (one, self-referencing, absolute).",
        "frameworks": {"nextjs": "metadata.alternates.canonical", "astro": "<link rel=canonical> in layout", "wordpress": "SEO plugin canonical", "static": "<link rel=canonical>"},
        "related": ["tech.index_conflict", "schema.missing"],
    },
    {
        "key": "indexability", "findings": ["robots.noindex", "robots.indexable", "onpage.snippet_directives"],
        "name": "Indexability signals (robots meta)", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "Whether the page's robots meta allows indexing, and whether snippet directives restrict previews.",
        "why": "A noindex robots meta tells engines to drop the page entirely - it cannot be retrieved or cited. Restrictive snippet directives (nosnippet, max-snippet:0) suppress the previews engines lift.",
        "how_to_fix": "Remove noindex if the page should be discoverable. Allow large image previews (max-image-preview:large) unless there is a reason not to.",
        "agent_guidance": "noindex is often deliberate (staging, thank-you pages) - confirm intent with the human before removing it; never blindly strip it. Snippet directives are usually safe to relax.",
        "verification": "Re-scan: robots.indexable PASS; snippet directives no longer restrictive.",
        "frameworks": {"nextjs": "metadata.robots", "astro": "<meta name=robots>", "wordpress": "SEO plugin index settings", "static": "<meta name=robots>"},
        "related": ["tech.x_robots_tag", "tech.index_conflict"],
    },
    {
        "key": "schema", "findings": ["schema.jsonld", "schema.missing", "schema.validation"],
        "name": "Structured data (JSON-LD)", "category": "deterministic_patch",
        "can_astova_generate": "deterministic", "agent_can_automate": "always", "human_review_required": False,
        "summary": "The page should carry valid JSON-LD (Organization/WebPage and any rich types) with required properties.",
        "why": "JSON-LD is the machine-readable layer engines use to extract entities, relationships and facts unambiguously, and to ground the page as a known entity. Missing or invalid schema forces the engine to infer from prose.",
        "how_to_fix": "Add schema.org JSON-LD (Organization + WebPage at minimum; Article/FAQ/Product where they fit), with all required properties for each type. The schema must match the visible content.",
        "agent_guidance": "Astova generates a correct Organization+WebPage @graph deterministically (and FAQPage from existing Q&A). Inject it as <script type=\"application/ld+json\"> in the head/layout. Use @graph for multiple entities. Be idempotent - do not duplicate existing schema. Never put claims in schema that are not on the page.",
        "verification": "Re-scan: schema.jsonld PASS (types detected), schema.validation PASS (required props present).",
        "frameworks": {"nextjs": "<script type=ld+json> in a server component/layout", "astro": "JSON-LD in the base layout", "wordpress": "SEO plugin schema", "static": "<script type=ld+json> in head"},
        "related": ["geo.entity", "geo.faq", "local.business_schema"],
    },
    {
        "key": "opengraph", "findings": ["opengraph"],
        "name": "Open Graph / social meta", "category": "deterministic_patch",
        "can_astova_generate": "no", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "Core Open Graph tags (og:title, og:description, og:image) should be present.",
        "why": "OG metadata gives engines and link-unfurlers a clean title/description/image to represent the page, reinforcing the page's identity and how it is presented when referenced.",
        "how_to_fix": "Add og:title, og:description, og:image (and ideally og:url, og:type, twitter:card) in the head.",
        "agent_guidance": "Set via the framework metadata layer, reusing the page title/description and a representative image. Low risk; values should be real and match the page.",
        "verification": "Re-scan: opengraph PASS (core tags present).",
        "frameworks": {"nextjs": "metadata.openGraph", "astro": "<meta property=og:*>", "wordpress": "SEO plugin social", "static": "<meta property=og:*>"},
        "related": ["title.missing", "meta.description.missing"],
    },
    {
        "key": "hreflang", "findings": ["onpage.hreflang"],
        "name": "hreflang", "category": "deterministic_patch",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "If the site uses hreflang, codes must be valid and include x-default.",
        "why": "For multilingual sites, correct hreflang tells engines which language/region variant to surface, so the right version is retrieved and cited for the right audience.",
        "how_to_fix": "Use valid language(-region) codes and include an x-default. Only add hreflang if the site genuinely has localized variants.",
        "agent_guidance": "Only act if localized variants exist - do not invent alternates. Fix invalid codes and add x-default. Requires knowing the real locale set, so confirm with the human.",
        "verification": "Re-scan: onpage.hreflang PASS (valid codes, x-default present).",
        "frameworks": {"nextjs": "metadata.alternates.languages", "astro": "<link rel=alternate hreflang>", "wordpress": "multilingual plugin", "static": "<link rel=alternate hreflang>"},
        "related": ["canonical"],
    },
    {
        "key": "image_alt", "findings": ["images.alt"],
        "name": "Image alt text", "category": "structured_ai_task",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "At least ~90% of images should have an alt attribute.",
        "why": "Engines (and the accessibility layer they respect) read alt text to understand image content - the only signal they have for what an image conveys.",
        "how_to_fix": "Add descriptive alt text to content images; use alt=\"\" for purely decorative ones.",
        "agent_guidance": "Writing good alt is editorial - describe what the image actually shows from real context, never guess. Decorative images get alt=\"\". Do not auto-fill every image with a generic string. Propose drafts for review.",
        "verification": "Re-scan: images.alt PASS (>=90% have alt).",
        "frameworks": {"nextjs": "alt on next/image", "astro": "alt on <img>", "wordpress": "media library alt", "static": "alt on <img>"},
        "related": ["onpage.images.dims"],
    },
    {
        "key": "image_dims", "findings": ["onpage.images.dims"],
        "name": "Image dimensions", "category": "deterministic_patch",
        "can_astova_generate": "no", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "At least ~80% of images should declare width and height.",
        "why": "Explicit dimensions prevent layout shift (a performance/experience signal) and help engines parse the page faster and more reliably.",
        "how_to_fix": "Add width and height attributes to images; add loading=\"lazy\" for below-the-fold images.",
        "agent_guidance": "Set real intrinsic dimensions (you must know the image's true size; do not guess aspect ratios). With next/image dimensions are required already. Low risk once real sizes are known.",
        "verification": "Re-scan: onpage.images.dims PASS (>=80% have width+height).",
        "frameworks": {"nextjs": "next/image width/height", "astro": "width/height on <img>", "wordpress": "theme/image handling", "static": "width/height attrs"},
        "related": ["images.alt", "perf.cls"],
    },
    {
        "key": "links", "findings": ["onpage.links", "onpage.outbound", "onpage.link_attrs", "onpage.crawlable_anchors", "onpage.jump_links"],
        "name": "Links and anchors", "category": "structured_ai_task",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "Anchors should be descriptive (not 'click here'), crawlable (real href), safe (noopener on _blank), and link to authoritative sources.",
        "why": "Engines read anchor text to understand what a link is about, follow real hrefs to traverse a site, and weigh outbound links to authoritative sources as a credibility signal.",
        "how_to_fix": "Replace generic anchors ('click here', 'read more') with descriptive text; ensure links use real href (not javascript:/onclick); add rel=noopener to target=_blank; cite authoritative external sources where relevant.",
        "agent_guidance": "Improving anchor text and adding noopener is mostly mechanical and safe. Choosing WHICH authoritative sources to cite is editorial - do not invent links. Do not change link destinations.",
        "verification": "Re-scan: onpage.links / link_attrs / crawlable_anchors PASS.",
        "frameworks": {"nextjs": "<Link>/<a> in components", "astro": "<a> in templates", "wordpress": "post links", "static": "<a> in HTML"},
        "related": ["geo.trust"],
    },
    {
        "key": "html_lang", "findings": ["onpage.lang"],
        "name": "HTML lang", "category": "deterministic_patch",
        "can_astova_generate": "no", "agent_can_automate": "always", "human_review_required": False,
        "summary": "The <html> element should declare a lang attribute.",
        "why": "lang tells engines the page's language, so it is retrieved and cited for the right-language queries.",
        "how_to_fix": "Add lang to the <html> element (e.g. lang=\"en\").",
        "agent_guidance": "Set the document language attribute (detect or confirm the language). Low risk and deterministic.",
        "verification": "Re-scan: onpage.lang PASS.",
        "frameworks": {"nextjs": "<html lang> in root layout", "astro": "<html lang> in layout", "wordpress": "language_attributes()", "static": "<html lang>"},
        "related": ["onpage.hreflang"],
    },
    {
        "key": "form_labels", "findings": ["onpage.form_labels"],
        "name": "Form labels", "category": "deterministic_patch",
        "can_astova_generate": "no", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "Form controls should have an associated label (label[for], aria-label, or a wrapping label).",
        "why": "Labels are an accessibility and clarity signal engines respect; unlabeled controls also signal a lower-quality page.",
        "how_to_fix": "Associate every input/select/textarea with a <label for>, aria-label, or wrap it in a <label>.",
        "agent_guidance": "Add labels mechanically; the label text should describe the field accurately. Low risk. Do not change form behaviour or names.",
        "verification": "Re-scan: onpage.form_labels PASS.",
        "frameworks": {"nextjs": "label/aria-label in JSX", "astro": "label in markup", "wordpress": "form plugin/theme", "static": "<label for>"},
        "related": [],
    },
    {
        "key": "url_structure", "findings": ["onpage.url"],
        "name": "URL structure", "category": "informational",
        "can_astova_generate": "no", "agent_can_automate": "never", "human_review_required": True,
        "summary": "The URL should be clean (lowercase, hyphenated, shallow, no query soup).",
        "why": "A clean, readable URL is a minor clarity signal; engines parse it as part of the page's identity.",
        "how_to_fix": "Prefer lowercase, hyphen-separated, shallow paths without tracking query strings. Usually only worth changing for new pages, with redirects from the old URL.",
        "agent_guidance": "Rarely safe to change an existing URL post-launch - it breaks links and requires redirects. Treat as advisory for new routes; do not rename live URLs without a redirect strategy and human sign-off.",
        "verification": "Re-scan the new URL: onpage.url PASS.",
        "frameworks": {"nextjs": "route/file path", "astro": "page file path", "wordpress": "permalinks", "static": "file path"},
        "related": ["tech.redirect"],
    },
    {
        "key": "https", "findings": ["tech.https"],
        "name": "HTTPS", "category": "informational",
        "can_astova_generate": "no", "agent_can_automate": "never", "human_review_required": True,
        "summary": "The page must be served over HTTPS.",
        "why": "Engines and AI crawlers deprioritise or skip insecure origins; HTTP content is treated as lower-trust source material.",
        "how_to_fix": "Obtain a TLS certificate and serve over HTTPS, redirecting all HTTP to HTTPS at the server/edge.",
        "agent_guidance": "Infrastructure, not code. Managed hosts (Vercel/Netlify/Cloudflare) provision HTTPS automatically; self-hosted needs a cert + listener config. An agent should report this, not attempt a code change.",
        "verification": "Re-scan: tech.https PASS (final URL is https).",
        "frameworks": {"nextjs": "host/CDN config", "astro": "host/CDN config", "wordpress": "host + SSL plugin", "static": "host/CDN config"},
        "related": ["tech.hsts", "tech.tls", "tech.mixed_content"],
    },
    {
        "key": "http_status", "findings": ["tech.status"],
        "name": "HTTP status", "category": "informational",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "The page should return a 2xx status.",
        "why": "A 4xx/5xx page cannot be read or cited; the engine gets an error instead of content.",
        "how_to_fix": "Fix the routing/server error so the URL returns 200, or correct the link if the URL is wrong.",
        "agent_guidance": "Diagnose the cause (missing route, server error, broken redirect). The fix may be code (a missing route) or infra (server config). Confirm the URL is meant to exist before creating it.",
        "verification": "Re-scan: tech.status PASS (2xx).",
        "frameworks": {"nextjs": "route/handler", "astro": "page/redirect", "wordpress": "permalink/redirect", "static": "file exists"},
        "related": ["tech.redirect"],
    },
    {
        "key": "redirects", "findings": ["tech.redirect", "tech.redirect.chain"],
        "name": "Redirects", "category": "informational",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "Avoid long redirect chains (more than two hops).",
        "why": "Each redirect hop adds latency and a chance for a crawler to drop off before reaching the content.",
        "how_to_fix": "Collapse multi-hop redirects to a single 301 to the final URL.",
        "agent_guidance": "Find the redirect rules (next.config/middleware, .htaccess, host config) and point intermediate hops straight to the destination. Verify you do not create a loop.",
        "verification": "Re-scan: redirect chain reduced to <=1 hop.",
        "frameworks": {"nextjs": "next.config redirects/middleware", "astro": "host redirects", "wordpress": "redirect plugin", "static": "host/_redirects"},
        "related": ["tech.status", "onpage.url"],
    },
    {
        "key": "hsts", "findings": ["tech.hsts"],
        "name": "HSTS", "category": "deterministic_patch",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "HTTPS pages should send a Strict-Transport-Security header.",
        "why": "HSTS is a security/trust signal that forces secure connections; it strengthens the trust posture engines read.",
        "how_to_fix": "Send a Strict-Transport-Security response header on HTTPS responses.",
        "agent_guidance": "Add the header where response headers are configured (next.config headers, middleware, server/CDN config). Be cautious with long max-age/preload - it is hard to undo; confirm intent.",
        "verification": "Re-scan: tech.hsts PASS.",
        "frameworks": {"nextjs": "next.config.mjs headers()", "astro": "host/CDN headers", "wordpress": "server config", "static": "host/_headers"},
        "related": ["tech.https", "tech.security_headers"],
    },
    {
        "key": "tls", "findings": ["tech.tls"],
        "name": "TLS certificate", "category": "informational",
        "can_astova_generate": "no", "agent_can_automate": "never", "human_review_required": True,
        "summary": "The TLS certificate must be valid and not near expiry.",
        "why": "An expired/invalid certificate breaks the secure fetch crawlers require; the page becomes unreadable.",
        "how_to_fix": "Renew the certificate before expiry (automate via Let's Encrypt / the host).",
        "agent_guidance": "Infrastructure, not code. Report it; renewal happens at the host/CA level.",
        "verification": "Re-scan: tech.tls PASS (valid, not near expiry).",
        "frameworks": {"nextjs": "host", "astro": "host", "wordpress": "host", "static": "host"},
        "related": ["tech.https"],
    },
    {
        "key": "mixed_content", "findings": ["tech.mixed_content", "tech.mixed_content.ok"],
        "name": "Mixed content", "category": "structured_ai_task",
        "can_astova_generate": "no", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "An HTTPS page should not load resources over http://.",
        "why": "Insecure subresources get blocked by browsers and degrade trust; they can also break rendering a crawler relies on.",
        "how_to_fix": "Change http:// resource references (scripts, styles, images, objects) to https:// or protocol-relative.",
        "agent_guidance": "Locate the http:// references in templates/components/config and switch them to https. Verify the resource is available over https. Do not change navigational links, only loaded subresources.",
        "verification": "Re-scan: tech.mixed_content.ok PASS (no insecure subresources).",
        "frameworks": {"nextjs": "component/asset URLs", "astro": "asset URLs", "wordpress": "content/theme URLs", "static": "asset URLs"},
        "related": ["tech.https"],
    },
    {
        "key": "viewport", "findings": ["tech.viewport"],
        "name": "Viewport", "category": "deterministic_patch",
        "can_astova_generate": "deterministic", "agent_can_automate": "always", "human_review_required": False,
        "summary": "The page should declare a mobile viewport meta.",
        "why": "A viewport meta signals a mobile-ready page; its absence flags an unoptimised experience engines factor in.",
        "how_to_fix": "Add <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">.",
        "agent_guidance": "Astova generates the standard viewport meta deterministically; inject it into the head/root layout. Low risk.",
        "verification": "Re-scan: tech.viewport PASS.",
        "frameworks": {"nextjs": "viewport export / root layout", "astro": "layout head", "wordpress": "theme header", "static": "<meta name=viewport>"},
        "related": [],
    },
    {
        "key": "robots_txt", "findings": ["tech.robots.missing", "tech.robots.ok", "tech.robots.ai", "tech.robots.sitemap"],
        "name": "robots.txt and AI crawler directives", "category": "deterministic_patch",
        "can_astova_generate": "deterministic", "agent_can_automate": "usually", "human_review_required": True,
        "summary": "A robots.txt should exist, allow the AI crawlers you want to be cited by, and reference the sitemap.",
        "why": "robots.txt is the first gate an AI crawler reads; disallowing GPTBot/ClaudeBot/PerplexityBot/Google-Extended/OAI-SearchBot makes you invisible to those engines regardless of content quality.",
        "how_to_fix": "Create/repair robots.txt to Allow the AI crawlers (in addition to *), and add a Sitemap: line.",
        "agent_guidance": "Astova generates a robots.txt allowing the AI crawlers deterministically. Place it at the site root (RB-4: public/ or app/robots.ts for Next). Before allowing AI crawlers, confirm the human wants them - some block AI deliberately. Do not also remove existing legitimate disallows for private paths.",
        "verification": "Re-scan: tech.robots.ok PASS, tech.robots.ai PASS (AI crawlers allowed), tech.robots.sitemap present.",
        "frameworks": {"nextjs": "public/robots.txt or app/robots.ts", "astro": "public/robots.txt", "wordpress": "root robots.txt / plugin", "static": "site-root robots.txt"},
        "related": ["geo.bot_access", "tech.sitemap", "tech.llms_txt"],
    },
    {
        "key": "sitemap", "findings": ["tech.sitemap", "tech.sitemap.missing", "tech.sitemap.invalid", "tech.sitemap.freshness"],
        "name": "XML sitemap", "category": "deterministic_patch",
        "can_astova_generate": "no", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "A valid, reasonably fresh XML sitemap should exist and be referenced.",
        "why": "A sitemap helps crawlers discover all pages efficiently and signals which content is current.",
        "how_to_fix": "Publish a valid sitemap.xml (or sitemap index), keep lastmod current, and reference it from robots.txt.",
        "agent_guidance": "For frameworks that generate sitemaps (Next app/sitemap.ts), wire it up - deterministic. For hand-built sites, generate from the route list. Ensure valid XML and a sitemap reference in robots.txt.",
        "verification": "Re-scan: tech.sitemap PASS (valid), freshness PASS.",
        "frameworks": {"nextjs": "app/sitemap.ts", "astro": "@astrojs/sitemap", "wordpress": "SEO plugin sitemap", "static": "generated sitemap.xml"},
        "related": ["tech.robots.sitemap"],
    },
    {
        "key": "index_conflict", "findings": ["tech.index_conflict"],
        "name": "Index conflict", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "never", "human_review_required": True,
        "summary": "The page is noindex yet listed in the sitemap - a contradictory signal.",
        "why": "Telling engines both 'do not index' and 'here is a page to index' is contradictory and wastes crawl trust; the engine cannot tell which intent is real.",
        "how_to_fix": "Decide the intent: either remove noindex (if it should be indexed) or remove it from the sitemap (if it should not).",
        "agent_guidance": "This is a decision, not a mechanical fix - the human must say whether the page should be indexed. Do not pick a side automatically.",
        "verification": "Re-scan: tech.index_conflict no longer fires.",
        "frameworks": {"nextjs": "robots meta + sitemap", "astro": "robots + sitemap", "wordpress": "SEO plugin", "static": "meta + sitemap"},
        "related": ["robots.noindex", "tech.sitemap"],
    },
    {
        "key": "resource_hints", "findings": ["tech.resource_hints"],
        "name": "Resource hints", "category": "structured_ai_task",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": False,
        "summary": "The page should avoid render-blocking scripts or use resource hints (preload/preconnect).",
        "why": "Faster, less-blocked rendering means a crawler reaches the content sooner and more reliably.",
        "how_to_fix": "Add async/defer to non-critical scripts; preload the critical asset; preconnect to required origins.",
        "agent_guidance": "Add defer/async to clearly non-critical scripts and preload the LCP asset. Performance-adjacent - measure; do not blindly reorder or remove scripts that other code depends on.",
        "verification": "Re-scan: tech.resource_hints PASS.",
        "frameworks": {"nextjs": "next/script strategy, next/font", "astro": "script directives", "wordpress": "perf plugin", "static": "defer/async, <link rel=preload>"},
        "related": ["perf.lcp", "perf.tbt"],
    },
    {
        "key": "x_robots", "findings": ["tech.x_robots_tag"],
        "name": "X-Robots-Tag", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "An X-Robots-Tag response header with noindex/none removes the page from engines.",
        "why": "Like a noindex meta but in the HTTP header - if set to noindex, the page cannot be retrieved or cited.",
        "how_to_fix": "Remove noindex/none from the X-Robots-Tag header if the page should be discoverable.",
        "agent_guidance": "Find where response headers are set (server/CDN/middleware). noindex may be deliberate - confirm before removing.",
        "verification": "Re-scan: tech.x_robots_tag no longer FAIL.",
        "frameworks": {"nextjs": "next.config headers/middleware", "astro": "host headers", "wordpress": "server config", "static": "host/_headers"},
        "related": ["robots.noindex", "tech.index_conflict"],
    },
    {
        "key": "compression", "findings": ["tech.compression"],
        "name": "Compression", "category": "informational",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": False,
        "summary": "Responses should be compressed (gzip/br/deflate/zstd).",
        "why": "Compression speeds delivery so crawlers fetch the page faster within their budget.",
        "how_to_fix": "Enable compression at the server/CDN.",
        "agent_guidance": "Usually a server/CDN setting (most managed hosts do it automatically). Report if it is off; rarely an in-repo change.",
        "verification": "Re-scan: tech.compression PASS.",
        "frameworks": {"nextjs": "host/CDN", "astro": "host/CDN", "wordpress": "host/cache plugin", "static": "host/CDN"},
        "related": ["perf.score"],
    },
    {
        "key": "security_headers", "findings": ["tech.security_headers"],
        "name": "Security headers", "category": "deterministic_patch",
        "can_astova_generate": "no", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "At least 3 of CSP, X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Permissions-Policy should be set.",
        "why": "Security headers are a trust/quality signal engines factor in and protect users arriving from AI referrals.",
        "how_to_fix": "Add the standard security headers to responses.",
        "agent_guidance": "In code-config frameworks this is deterministic (next.config headers(), middleware, _headers). CSP can break a site if too strict - allow inline styles/fonts/needed origins and test. The other four are safe.",
        "verification": "Re-scan: tech.security_headers PASS (>=3 present).",
        "frameworks": {"nextjs": "next.config.mjs headers()", "astro": "host/_headers", "wordpress": "server config/plugin", "static": "host/_headers"},
        "related": ["tech.hsts"],
    },
    {
        "key": "llms_txt", "findings": ["tech.llms_txt"],
        "name": "llms.txt", "category": "deterministic_patch",
        "can_astova_generate": "deterministic", "agent_can_automate": "always", "human_review_required": False,
        "summary": "An llms.txt file at the site root summarises the site for AI consumers.",
        "why": "llms.txt is an emerging convention that gives AI engines a curated map of your most important content and context.",
        "how_to_fix": "Add an llms.txt at the site root with the site name, a one-line description, and links to key pages.",
        "agent_guidance": "Astova generates a starter llms.txt deterministically. Place it at the site root (RB-4). Low risk; refine the curated links to your real key pages.",
        "verification": "Re-scan: tech.llms_txt PASS.",
        "frameworks": {"nextjs": "public/llms.txt", "astro": "public/llms.txt", "wordpress": "root llms.txt", "static": "site-root llms.txt"},
        "related": ["tech.robots.ok"],
    },
    {
        "key": "no_content", "findings": ["geo.no_content"],
        "name": "No readable content", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "The page HTML has almost no visible text - usually a client-rendered shell.",
        "why": "Many AI crawlers do not run JavaScript. If content only exists after the browser hydrates, those crawlers see a blank page and cannot read, chunk or cite anything.",
        "how_to_fix": "Get the real content into the server HTML via SSR, static generation, or prerendering.",
        "agent_guidance": "Architectural, not copy. Find the route/component; check for client-only rendering ('use client', useEffect data fetch, client:only). Move the existing content source into a server-rendered path - never invent body copy to fill the page. Verify the build and that data is available at render time.",
        "verification": "Re-fetch without JS: visible word count clears the floor and content is present.",
        "frameworks": {"nextjs": "Server Components / getStaticProps", "astro": "static .astro/.md, not client:only", "wordpress": "render server-side", "static": "put copy in the HTML"},
        "related": ["geo.js_rendered", "geo.aeo", "geo.thin_content"],
    },
    {
        "key": "aeo", "findings": ["geo.aeo", "geo.frontload", "geo.intro_quality"],
        "name": "Up-front answer (AEO core)", "category": "structured_ai_task",
        "can_astova_generate": "ai_assisted", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "The page should open with a direct, complete, non-promotional answer in the first ~150 words (ideally before 220).",
        "why": "AI engines weight the top of the page and lift the first self-contained declarative sentence. If the opening is a heading, tagline or marketing pitch, there is no clean answer chunk to cite, so a competitor who led with the answer gets cited.",
        "how_to_fix": "Open with a real <p> of at least 12 words that directly answers the page's question, ending in a full stop, before the 220-word mark. Strip marketing language and exclamation marks from the opening.",
        "agent_guidance": "Locate where the intro is authored (MDX/markdown/CMS/component prop). Read the whole page to learn the real answer, then move or paraphrase it into the opening - preserving meaning, inventing nothing. Demote marketing copy below the answer. Astova can AI-draft a candidate (these are ai_draftable), but the draft must be fact-checked and human-reviewed.",
        "verification": "Re-scan: geo.frontload PASS, geo.aeo offset under 220 (PASS), geo.intro_quality no longer flags promo language.",
        "frameworks": {"nextjs": "intro MDX/component text", "astro": ".md/.astro intro", "wordpress": "post body / hero block", "static": "first <p> after <h1>"},
        "related": ["geo.definitive", "geo.summary_bullets", "geo.no_content"],
    },
    {
        "key": "definitive", "findings": ["geo.definitive"],
        "name": "Definitive language", "category": "structured_ai_task",
        "can_astova_generate": "ai_assisted", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "Keep hedging language ('might', 'usually', 'arguably') under ~2% of words.",
        "why": "A hedged sentence is a weak answer - it signals the source is unsure, so engines prefer a competitor stating the same thing plainly. Definitive claims are cited roughly twice as often.",
        "how_to_fix": "Rewrite filler hedges into direct statements where the claim is in fact certain; keep hedges only where genuine uncertainty exists.",
        "agent_guidance": "Find the hedge words; for each judge filler vs load-bearing. Remove filler; never assert certainty the author deliberately avoided or strip hedges from legal/medical/safety copy. ai_draftable, but changing claim strength is a meaning change - propose for review.",
        "verification": "Re-scan: geo.definitive ratio under 0.02 (PASS); no rewritten sentence now overstates.",
        "frameworks": {"nextjs": "body MDX/component", "astro": ".md/.astro body", "wordpress": "post body", "static": "<p> elements"},
        "related": ["geo.aeo", "geo.data_density"],
    },
    {
        "key": "structure", "findings": ["geo.structure", "geo.summary_bullets"],
        "name": "Extractable structure and summary bullets", "category": "structured_ai_task",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "The page should contain real content lists/tables (not just menus), and a summary list near the top.",
        "why": "AI Overviews and answer engines disproportionately lift list and table formatting - a bullet or row is already a clean, self-contained unit to quote. All-prose pages give nothing pre-chunked.",
        "how_to_fix": "Add a genuine content list or table near the answer, and a concise summary bullet list within the first ~350 words. Items should be substantive (more than four words), not navigation links.",
        "agent_guidance": "Extract 3-5 of the page's existing key points into a summary list right after the intro; mark up naturally enumerable content (steps, specs, comparisons) as a real list/table. Do not invent items or turn a nav menu into a 'content list'. Faithful restatement only.",
        "verification": "Re-scan: geo.structure PASS (content list/table) and geo.summary_bullets PASS (non-nav list before offset 350).",
        "frameworks": {"nextjs": "MDX/component list", "astro": ".md list", "wordpress": "List/Table block", "static": "<ul>/<table>"},
        "related": ["geo.chunking", "geo.aeo", "geo.faq"],
    },
    {
        "key": "faq", "findings": ["geo.faq", "geo.qa_headings"],
        "name": "FAQ and Q&A", "category": "structured_ai_task",
        "can_astova_generate": "deterministic", "agent_can_automate": "usually", "human_review_required": True,
        "summary": "Where appropriate, use question-style headings with direct answers, plus FAQPage JSON-LD that mirrors them.",
        "why": "People ask engines questions; engines lift matching Q&A pairs almost verbatim. A heading mirroring the real prompt followed by a direct answer is the cleanest possible chunk, and FAQPage schema spells the pairs out machine-readably.",
        "how_to_fix": "Phrase relevant headings as the real questions, each immediately followed by a direct answer (>=8 words). Add FAQPage JSON-LD whose Q&A matches the visible copy exactly.",
        "agent_guidance": "If visible Q&A already exists, generating matching FAQPage JSON-LD is deterministic and low-risk (Astova does this) - never invent or paraphrase answers in the schema. Writing NEW answer copy is high faithfulness risk; draw answers from content already on the page and propose for review.",
        "verification": "Re-scan: geo.faq PASS (schema and/or >=2 pairs), geo.qa_headings PASS; JSON-LD matches the rendered Q&A.",
        "frameworks": {"nextjs": "MDX Q&A + JSON-LD in head", "astro": ".md Q&A + JSON-LD", "wordpress": "FAQ block/plugin", "static": "question <h2> + answer <p> + JSON-LD"},
        "related": ["schema.missing", "geo.aeo"],
    },
    {
        "key": "depth", "findings": ["geo.thin_content", "geo.depth"],
        "name": "Content depth", "category": "structured_ai_task",
        "can_astova_generate": "ai_assisted", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "Pages under ~300 words are flagged thin.",
        "why": "Engines prefer sources thorough enough to answer follow-ups and supply context around the cited chunk; a very short page rarely has the substance to be the cited authority.",
        "how_to_fix": "Expand with substantive, accurate coverage - definitions, how/why, examples, supporting data - only with real content; padding hurts every other GEO signal.",
        "agent_guidance": "Highest fabrication risk of any GEO fix. Do NOT pad. Gather real material from related pages/docs/product data/CMS or the human, expand from that, structure as extractable chunks, and surface as a draft for review. Never invent statistics or claims to hit a word count.",
        "verification": "Re-scan: geo.depth PASS (>=300 words), no regression in geo.aeo/geo.chunking, no invented facts.",
        "frameworks": {"nextjs": "MDX/component", "astro": ".md body", "wordpress": "post body", "static": "content sections"},
        "related": ["geo.no_content", "geo.chunking", "geo.data_density"],
    },
    {
        "key": "chunking", "findings": ["geo.chunking"],
        "name": "Extractable chunks", "category": "structured_ai_task",
        "can_astova_generate": "no", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "Break the body into discrete ~20-80 word paragraphs rather than walls of text.",
        "why": "Engines lift self-contained chunks; a 600-word block forces them to quote too much or guess boundaries, so a well-chunked competitor wins the citation.",
        "how_to_fix": "Split walls into discrete paragraphs each making one self-contained point, with subheadings where topics change. Keep at least three substantive paragraphs.",
        "agent_guidance": "Purely structural splitting of existing prose (inserting paragraph breaks and accurate subheadings) is low risk - do not change the wording. It becomes editorial if you add connective text or subheading copy; keep that faithful and minimal.",
        "verification": "Re-scan: geo.chunking PASS (>=3 substantive paragraphs, few walls).",
        "frameworks": {"nextjs": "MDX paragraphs", "astro": ".md paragraphs", "wordpress": "paragraph blocks", "static": "<p> elements + headings"},
        "related": ["geo.structure", "geo.thin_content"],
    },
    {
        "key": "data_density", "findings": ["geo.data_density"],
        "name": "Quotable data", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "never", "human_review_required": True,
        "summary": "A substantial page making claims with no concrete figures is flagged.",
        "why": "Engines disproportionately cite pages with hard, verifiable data - a specific number is exactly the quotable, checkable fact an answer needs.",
        "how_to_fix": "Add real statistics, prices, dates and measurements that support the page's claims; replace vague quantifiers with specific figures - true numbers only.",
        "agent_guidance": "Never autonomous. Adding numbers is the highest-fabrication-risk edit possible. Only surface figures you can source verbatim from the codebase, a dataset, or human input, note the source, and confirm. Never invent a plausible-looking statistic.",
        "verification": "Re-scan: geo.data_density PASS; every added figure independently verified against its source.",
        "frameworks": {"nextjs": "MDX/data files", "astro": ".md/data", "wordpress": "post body/data block", "static": "content"},
        "related": ["geo.definitive", "geo.thin_content"],
    },
    {
        "key": "trust", "findings": ["geo.trust"],
        "name": "Trust and E-E-A-T", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "never", "human_review_required": True,
        "summary": "The page should carry at least 3 of: author byline, published/updated date, About+Contact links, Organization/Person schema with sameAs.",
        "why": "Engines decide which sources are safe to repeat as fact; clear authorship, dating and entity identity mark the page as accountable and raise citation likelihood. Anonymous, undated pages get skipped.",
        "how_to_fix": "Add the missing signals using real values: a real author byline, a true publish/update date mirrored in schema, About and Contact links, and entity JSON-LD with sameAs.",
        "agent_guidance": "Never invent the values - an author name, date or sameAs URL are identity facts. Ask the human for them, wire the real values into the template, emit the schema. If a value cannot be supplied, leave that signal out and report it.",
        "verification": "Re-scan: geo.trust PASS (>=3 of 4 signals).",
        "frameworks": {"nextjs": "article template + JSON-LD", "astro": "frontmatter + JSON-LD", "wordpress": "theme byline/date + SEO schema", "static": "byline + <time> + footer links + JSON-LD"},
        "related": ["geo.freshness", "geo.entity"],
    },
    {
        "key": "freshness", "findings": ["geo.freshness"],
        "name": "Content freshness", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "never", "human_review_required": True,
        "summary": "Expose a real published/updated date; content older than ~18 months reads as stale.",
        "why": "Engines preferentially cite content they can confirm is current. An undated page forces a guess at recency; a stale one is demoted for a fresher competitor.",
        "how_to_fix": "Add a visible published/last-updated date mirrored in datePublished/dateModified. If the content is genuinely old, refresh it and then update the date.",
        "agent_guidance": "Never auto-stamp the current date - that fabricates freshness. Wire a real, human-supplied date in; if the content actually changed in this edit, update dateModified to the true date, otherwise leave it and flag it.",
        "verification": "Re-scan: geo.freshness PASS (latest date within ~18 months).",
        "frameworks": {"nextjs": "template date + dateModified schema", "astro": "frontmatter dates", "wordpress": "modified date + SEO schema", "static": "<time datetime> + JSON-LD"},
        "related": ["geo.trust"],
    },
    {
        "key": "entity", "findings": ["geo.entity"],
        "name": "Entity grounding (sameAs)", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "never", "human_review_required": True,
        "summary": "Organization/Person JSON-LD should carry sameAs links to a knowledge base or several authoritative profiles.",
        "why": "LLMs reason over entities, not strings. sameAs to Wikipedia/Wikidata or authoritative profiles ties the page to a node the model recognises and trusts, making correct attribution and citation far more likely.",
        "how_to_fix": "Add/extend Organization/Person JSON-LD with a sameAs array of the entity's real, official profiles (and Wikipedia/Wikidata if an entry exists).",
        "agent_guidance": "Never invent sameAs URLs - they are identity claims. Ask the human for the real official profile links; scaffold the schema and fill with verified URLs only. Report any that cannot be supplied.",
        "verification": "Re-scan: geo.entity PASS (knowledge-base link or >=2 authoritative profiles).",
        "frameworks": {"nextjs": "Organization JSON-LD in layout", "astro": "JSON-LD in base layout", "wordpress": "SEO plugin knowledge graph", "static": "Organization JSON-LD"},
        "related": ["geo.trust", "schema.missing", "local.business_schema"],
    },
    {
        "key": "js_rendered", "findings": ["geo.js_rendered"],
        "name": "JavaScript-dependent content", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "Too much of the page's content appears only after JavaScript runs; non-JS AI crawlers see a shell.",
        "why": "ChatGPT, Claude and Perplexity crawlers largely do not execute JavaScript. If your headline, body, H1 or schema only exist after a client render, those engines retrieve a near-empty page and you are invisible to them.",
        "how_to_fix": "Serve the key content in the initial HTML via SSR, static generation, or prerendering.",
        "agent_guidance": "Architectural. Identify client-only rendering (useEffect data fetch, client:only, post-mount loading) and move that content to a server-rendered path. Preserve hydration - server markup must match the client tree, or you get mismatches; keep genuinely interactive pieces as islands. Verify the H1 and JSON-LD now appear in raw HTML.",
        "verification": "Re-scan with render: render-only share under 15% (PASS); H1/schema present in raw HTML.",
        "frameworks": {"nextjs": "Server Components / SSG", "astro": "static-first, islands for interactivity", "wordpress": "server-render; avoid JS page builders", "static": "content already in HTML"},
        "related": ["geo.no_content", "geo.bot_access"],
    },
    {
        "key": "bot_access", "findings": ["geo.bot_access"],
        "name": "AI crawler access", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "An AI crawler (e.g. GPTBot) is blocked or served far less content than a normal browser.",
        "why": "If an AI crawler cannot fetch your page, it cannot cite you - full stop. Many sites unknowingly block GPTBot/ClaudeBot/PerplexityBot at the CDN/WAF, or serve them a consent/JS wall, while serving humans normally.",
        "how_to_fix": "Allow the AI crawlers (GPTBot, ClaudeBot, anthropic-ai, PerplexityBot, Google-Extended, OAI-SearchBot) in both robots.txt and at the CDN/WAF, and exempt them from consent/JS interstitials.",
        "agent_guidance": "Determine whether the block is in-repo (robots.txt, edge middleware) or at the CDN/WAF. Fix the in-repo parts; for the CDN/WAF (e.g. Cloudflare 'Block AI bots'), report the exact setting and confirm the human wants these crawlers allowed before changing it - the block may be deliberate. Never weaken security beyond allowing the named crawlers.",
        "verification": "Re-scan as the bot: geo.bot_access PASS (matching status and word count).",
        "frameworks": {"nextjs": "robots.txt / middleware / host bot settings", "astro": "robots / host", "wordpress": "security plugin / CDN", "static": "host/CDN bot settings"},
        "related": ["tech.robots.ai", "geo.js_rendered"],
    },
    {
        "key": "performance", "findings": ["perf.score", "perf.lcp", "perf.cls", "perf.tbt", "perf.fcp", "perf.si", "perf.field"],
        "name": "Performance (Core Web Vitals)", "category": "structured_ai_task",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": False,
        "summary": "Lab (Lighthouse) and real-user (CrUX) speed metrics: overall score, LCP, CLS, TBT, FCP, Speed Index, field data.",
        "why": "Crawlers operate under time/resource budgets, and where engines drive referral traffic a slow, shifting page undercuts the click. Not the primary GEO lever, but a real signal and cost.",
        "how_to_fix": "Fix the specific failing metric: LCP (preload/compress the largest element, cut render-blocking CSS/JS), CLS (set image/embed dimensions), TBT (break up/defer JS), FCP/SI (reduce server response and render-blocking).",
        "agent_guidance": "Read which metric failed - do not optimise blindly. Apply targeted, safe changes (image dimensions, lazy-load, defer/async, preload the LCP asset). Do NOT blindly remove scripts, change bundlers or strip CSS - measure before/after and re-run PageSpeed.",
        "verification": "Re-run the performance check: the failing metric and perf.score move toward PASS (field data lags - confirm lab first).",
        "frameworks": {"nextjs": "next/image, next/font, dynamic imports, SSR", "astro": "minimise islands, image integration", "wordpress": "caching + image optimisation plugins", "static": "image dims, preload, defer/async, inline critical CSS"},
        "related": ["geo.js_rendered", "tech.resource_hints"],
    },
    {
        "key": "local", "findings": ["local.business_schema", "local.nap", "local.hours", "local.geo", "local.gbp"],
        "name": "Local business", "category": "human_decision",
        "can_astova_generate": "ai_assisted", "agent_can_automate": "never", "human_review_required": True,
        "summary": "For local-business pages: LocalBusiness schema, consistent NAP (name/address/phone), hours, geo coordinates, and a Google Business Profile link.",
        "why": "For 'near me' and local queries, engines assemble answers from structured business data - they need a machine-readable address, phone, hours and coordinates to answer. Complete, consistent LocalBusiness schema is what engines can turn into a local answer.",
        "how_to_fix": "Add LocalBusiness (or the right subtype) JSON-LD with the real name, full address, phone, geo and hours; show consistent NAP; add a GBP link. Every value must match the real business and the real Google listing.",
        "agent_guidance": "Never automate the values - address, phone, hours, coordinates and GBP URL are business facts, and a wrong value actively harms (engines cross-check the real listing). Astova can scaffold a LocalBusiness schema PLACEHOLDER, but the human must supply every value; ensure the visible NAP matches the schema exactly. Leave any unconfirmed value blank and flag it.",
        "verification": "Re-scan the local page: local.business_schema and local.nap PASS once real values are present.",
        "frameworks": {"nextjs": "LocalBusiness JSON-LD from CMS/config", "astro": "schema from frontmatter", "wordpress": "local-SEO plugin", "static": "hand-written LocalBusiness JSON-LD"},
        "related": ["geo.entity", "schema.missing"],
    },
    {
        "key": "schema_entity_conflicts",
        "findings": ["schema.duplicate_organization", "schema.duplicate_localbusiness",
                     "schema.duplicate_website", "schema.conflicting_organization_name",
                     "schema.conflicting_organization_url", "schema.conflicting_organization_logo",
                     "schema.duplicate_id_conflict"],
        "name": "Schema entity duplication & conflicts", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "There should be ONE Organization / LocalBusiness / WebSite entity per role, with agreeing name, url and logo, and each @id identifying exactly one entity.",
        "why": "AI engines resolve a page to a known ENTITY before they cite it. Duplicate or contradictory Organization/WebSite nodes (two names, two URLs, two logos, or one @id reused for different types) make that resolution ambiguous, so the engine can't confidently ground the page to your brand.",
        "how_to_fix": "Keep a single Organization/WebSite/LocalBusiness entity and reference it elsewhere by @id; make name/url/logo agree across nodes; give every distinct entity its own @id.",
        "agent_guidance": "Detected deterministically by counting entities and comparing their name/url/logo and @id-to-type mapping. The agent can merge obvious duplicates and de-conflict @ids mechanically, BUT choosing the CORRECT name/url/logo is a business-identity decision - confirm with the human; never guess which value is right or delete an entity blind.",
        "verification": "Re-scan: the schema.duplicate_* / schema.conflicting_* / schema.duplicate_id_conflict findings clear once one consistent entity remains.",
        "frameworks": {"nextjs": "single JSON-LD @graph in the root layout", "astro": "one schema block in the base layout", "wordpress": "one SEO/schema plugin (avoid two emitting schema)", "static": "one <script type=ld+json> @graph"},
        "related": ["schema.missing", "geo.entity", "local.business_schema"],
    },
    {
        "key": "schema_graph_wiring",
        "findings": ["schema.missing_id", "schema.orphan_node", "schema.breadcrumb_disconnected"],
        "name": "Schema graph wiring", "category": "structured_ai_task",
        "can_astova_generate": "no", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "In a multi-entity @graph, main entities should carry a stable @id, nodes should be referenced (no orphans), and a BreadcrumbList should be attached to the WebPage via breadcrumb.",
        "why": "A connected graph lets engines follow relationships (this page is published by this Organization; this breadcrumb belongs to this page). Missing @ids and orphan/disconnected nodes leave the relationships implicit, so the engine sees loose fragments instead of one coherent entity graph.",
        "how_to_fix": "Add a stable @id to each main entity (e.g. https://site/#org), reference nodes by @id from their parent, and point the WebPage's breadcrumb property at the BreadcrumbList's @id.",
        "agent_guidance": "Detected deterministically from the @id graph (which nodes are referenced, whether a breadcrumb link exists). Wiring is mechanical and low-risk - add @ids and references using the entities' own URLs; do not invent new entities or change any factual values.",
        "verification": "Re-scan: schema.missing_id / schema.orphan_node / schema.breadcrumb_disconnected clear once the graph is connected.",
        "frameworks": {"nextjs": "@id + references in the JSON-LD @graph", "astro": "@graph with @id links", "wordpress": "schema plugin graph settings", "static": "hand-written @graph with @id"},
        "related": ["schema.missing", "schema.duplicate_id_conflict"],
    },
    {
        "key": "schema_searchaction", "findings": ["schema.website_missing_searchaction"],
        "name": "WebSite SearchAction", "category": "deterministic_patch",
        "can_astova_generate": "deterministic", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "When the site has a search box, the WebSite schema should declare a SearchAction potentialAction.",
        "why": "A SearchAction tells engines how to search your site directly, which is how sitelinks search boxes and some answer-engine deep links are generated - it exposes your own search as a machine-usable action.",
        "how_to_fix": "Add a potentialAction SearchAction to the WebSite entity with an EntryPoint urlTemplate pointing at your real search URL and a query-input.",
        "agent_guidance": "Astova generates the SearchAction snippet deterministically (with a urlTemplate placeholder). Only the search-URL path is site-specific - set it to your real search endpoint; the rest is boilerplate. Only add this if the site genuinely has search.",
        "verification": "Re-scan: schema.website_missing_searchaction clears once a valid SearchAction is present.",
        "frameworks": {"nextjs": "SearchAction in the WebSite JSON-LD", "astro": "SearchAction in base-layout schema", "wordpress": "SEO plugin sitelinks-search setting", "static": "SearchAction in WebSite JSON-LD"},
        "related": ["schema.missing"],
    },
    {
        "key": "schema_sameas", "findings": ["schema.invalid_sameas", "schema.weak_sameas"],
        "name": "Schema sameAs quality", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "sameAs values should be valid absolute http(s) profile URLs, not empty or malformed.",
        "why": "sameAs links your entity to authoritative profiles (Wikipedia, Crunchbase, official socials) that engines already trust - it's a primary entity-grounding signal. Invalid or empty sameAs wastes the slot and can break entity reconciliation.",
        "how_to_fix": "Fix or remove malformed sameAs entries; populate an empty sameAs with the entity's real, official profile URLs (or remove the empty property).",
        "agent_guidance": "Astova detects malformed/empty sameAs deterministically. Fixing a malformed URL is mechanical, but CHOOSING which authoritative profiles to add is identity work - never invent profile URLs; confirm the real ones with the human.",
        "verification": "Re-scan: schema.invalid_sameas / schema.weak_sameas clear once sameAs holds valid real URLs.",
        "frameworks": {"nextjs": "sameAs array in Organization JSON-LD", "astro": "sameAs in schema block", "wordpress": "social profiles in SEO plugin", "static": "sameAs array in JSON-LD"},
        "related": ["geo.entity", "schema.missing"],
    },
    {
        "key": "schema_article_rel",
        "findings": ["schema.article_missing_publisher", "schema.article_missing_author"],
        "name": "Article publisher & author", "category": "human_decision",
        "can_astova_generate": "no", "agent_can_automate": "sometimes", "human_review_required": True,
        "summary": "Article / BlogPosting schema should declare both a publisher (Organization) and an author (Person or Organization).",
        "why": "Engines attribute content to entities. An Article with no author/publisher can't be tied to a known author or brand, which weakens its trust/E-E-A-T grounding and makes it ineligible for Article rich results.",
        "how_to_fix": "Add publisher (your Organization, ideally by @id) and author (the real Person or Organization) to the Article schema.",
        "agent_guidance": "Detected deterministically (the property is absent). Wiring publisher to the existing Organization @id is mechanical; the AUTHOR is a real person's identity - never invent an author name; use the real byline or confirm with the human.",
        "verification": "Re-scan: schema.article_missing_publisher / schema.article_missing_author clear once the relationships are present.",
        "frameworks": {"nextjs": "author/publisher in Article JSON-LD", "astro": "author/publisher in schema", "wordpress": "author from the post; publisher from SEO plugin", "static": "author/publisher in JSON-LD"},
        "related": ["geo.trust", "geo.entity"],
    },
    {
        "key": "schema_url_hygiene",
        "findings": ["schema.canonical_mismatch", "schema.insecure_url",
                     "schema.image_missing_dimensions", "schema.generic_type"],
        "name": "Schema URL & type hygiene", "category": "structured_ai_task",
        "can_astova_generate": "no", "agent_can_automate": "usually", "human_review_required": False,
        "summary": "Schema URLs should match the page canonical, use https on an https page, images should declare dimensions, and types should be specific (not bare Thing).",
        "why": "Engines cross-check schema URLs against the page. A schema url that disagrees with the canonical, http URLs on an https page, dimensionless images, or an over-generic Thing type all make the markup less trustworthy and harder to use cleanly.",
        "how_to_fix": "Point the main entity's url at the page canonical; switch http URLs to https; add width/height to schema ImageObjects; use the most specific schema.org type that fits.",
        "agent_guidance": "All detected deterministically. Aligning the canonical, switching to https (only when the https URL genuinely exists), and adding real image dimensions are mechanical; choosing a more specific type needs knowing what the page actually is - confirm if unsure. Never point at a URL you haven't verified exists.",
        "verification": "Re-scan: schema.canonical_mismatch / schema.insecure_url / schema.image_missing_dimensions / schema.generic_type clear once corrected.",
        "frameworks": {"nextjs": "canonical + https URLs in JSON-LD", "astro": "schema URLs in layout", "wordpress": "SEO plugin canonical/schema", "static": "URLs in JSON-LD"},
        "related": ["canonical", "tech.mixed_content"],
    },
]

# Build the finding-id -> card index once at import.
_INDEX: dict[str, dict] = {}
for _c in _CARDS:
    for _fid in _c["findings"]:
        _INDEX[_fid] = _c


def _shape(card: dict, finding_id: str | None) -> dict:
    """Return the public, machine-readable explanation object for a card."""
    out = {
        "finding_id": finding_id,
        "card": card["key"],
        "covers": card["findings"],
        "name": card["name"],
        "summary": card["summary"],
        "confidence": "verified",
        "category": card["category"],
        "can_astova_generate": card["can_astova_generate"],
        "agent_can_automate": card["agent_can_automate"],
        "human_review_required": card["human_review_required"],
        "why_it_matters": card["why"],
        "how_to_fix": card["how_to_fix"],
        "agent_guidance": card["agent_guidance"],
        "framework_examples": card["frameworks"],
        "verification": card["verification"],
        "related_findings": card["related"],
        "reference": "docs/KNOWLEDGE_BASE.md",
    }
    return out


def explain(finding_id: str) -> dict | None:
    """Structured explanation for a single finding id (or a card key). None if unknown.

    Accepts any finding id the engine can emit (e.g. "geo.aeo", "title.length") or a card key
    (e.g. "aeo"). Returns the machine-readable fix knowledge an AI coding agent needs.
    """
    if not finding_id:
        return None
    fid = finding_id.strip()
    card = _INDEX.get(fid)
    if card is None:
        # allow lookup by card key as a convenience
        card = next((c for c in _CARDS if c["key"] == fid), None)
        if card is None:
            return None
        return _shape(card, None)
    return _shape(card, fid)


def list_cards() -> list[dict]:
    """A lightweight index of every card (for GET /findings)."""
    return [
        {
            "card": c["key"],
            "name": c["name"],
            "covers": c["findings"],
            "category": c["category"],
            "can_astova_generate": c["can_astova_generate"],
            "agent_can_automate": c["agent_can_automate"],
        }
        for c in _CARDS
    ]


def known_finding_ids() -> list[str]:
    """Every finding id the knowledge base can explain."""
    return sorted(_INDEX.keys())
